# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: usps_intelligent_barcode 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "usps_intelligent_barcode"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Wayne Conrad"]
  s.date = "2015-06-13"
  s.description = "A pure Ruby library to generate a USPS Intelligent Mail barcode.  It generates the string of characters to print with one of the USPS Intelligent Mail barcode fonts."
  s.email = "wconrad@yagni.com"
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.markdown"
  ]
  s.files = [
    ".travis.yml",
    "CHANGELOG.markdown",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.md",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "examples/example.rb",
    "lib/USPS-intelligent-barcode.rb",
    "lib/USPS-intelligent-barcode/bar_map.rb",
    "lib/USPS-intelligent-barcode/bar_position.rb",
    "lib/USPS-intelligent-barcode/bar_symbol.rb",
    "lib/USPS-intelligent-barcode/bar_to_character_mapping.yml",
    "lib/USPS-intelligent-barcode/barcode.rb",
    "lib/USPS-intelligent-barcode/barcode_id.rb",
    "lib/USPS-intelligent-barcode/character_position.rb",
    "lib/USPS-intelligent-barcode/codeword_map.rb",
    "lib/USPS-intelligent-barcode/codeword_to_character_mapping.yml",
    "lib/USPS-intelligent-barcode/crc.rb",
    "lib/USPS-intelligent-barcode/mailer_id.rb",
    "lib/USPS-intelligent-barcode/numeric_conversions.rb",
    "lib/USPS-intelligent-barcode/routing_code.rb",
    "lib/USPS-intelligent-barcode/serial_number.rb",
    "lib/USPS-intelligent-barcode/service_type.rb",
    "lib/usps_intelligent_barcode.rb",
    "lib/usps_intelligent_barcode/bar_map.rb",
    "lib/usps_intelligent_barcode/bar_position.rb",
    "lib/usps_intelligent_barcode/bar_symbol.rb",
    "lib/usps_intelligent_barcode/bar_to_character_mapping.yml",
    "lib/usps_intelligent_barcode/barcode.rb",
    "lib/usps_intelligent_barcode/barcode_id.rb",
    "lib/usps_intelligent_barcode/character_position.rb",
    "lib/usps_intelligent_barcode/codeword_map.rb",
    "lib/usps_intelligent_barcode/codeword_to_character_mapping.yml",
    "lib/usps_intelligent_barcode/crc.rb",
    "lib/usps_intelligent_barcode/mailer_id.rb",
    "lib/usps_intelligent_barcode/numeric_conversions.rb",
    "lib/usps_intelligent_barcode/routing_code.rb",
    "lib/usps_intelligent_barcode/serial_number.rb",
    "lib/usps_intelligent_barcode/service_type.rb",
    "spec/bar_map_spec.rb",
    "spec/bar_position_spec.rb",
    "spec/bar_symbol_spec.rb",
    "spec/barcode_id_spec.rb",
    "spec/barcode_spec.rb",
    "spec/character_position_spec.rb",
    "spec/codeword_map_spec.rb",
    "spec/crc_spec.rb",
    "spec/mailer_id_spec.rb",
    "spec/numeric_conversions_spec.rb",
    "spec/routing_code_spec.rb",
    "spec/serial_number_spec.rb",
    "spec/service_type_spec.rb",
    "spec/spec_helper.rb",
    "usps_intelligent_barcode.gemspec"
  ]
  s.homepage = "http://github.com/wconrad/usps_intelligent_barcode"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Generates a USPS Intelligent Mail Barcode."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<andand>, ["~> 1.3"])
      s.add_runtime_dependency(%q<memoizer>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.3"])
      s.add_development_dependency(%q<rspec-its>, ["~> 1.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.10.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.8.5"])
      s.add_development_dependency(%q<rake>, ["~> 10.0"])
    else
      s.add_dependency(%q<andand>, ["~> 1.3"])
      s.add_dependency(%q<memoizer>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, ["~> 3.3"])
      s.add_dependency(%q<rspec-its>, ["~> 1.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.10.0"])
      s.add_dependency(%q<yard>, ["~> 0.8.5"])
      s.add_dependency(%q<rake>, ["~> 10.0"])
    end
  else
    s.add_dependency(%q<andand>, ["~> 1.3"])
    s.add_dependency(%q<memoizer>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, ["~> 3.3"])
    s.add_dependency(%q<rspec-its>, ["~> 1.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.10.0"])
    s.add_dependency(%q<yard>, ["~> 0.8.5"])
    s.add_dependency(%q<rake>, ["~> 10.0"])
  end
end

